// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:extension_methods_test/mixin/json_extension.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'FormDeclaration',
            r'.FormDeclaration',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 13],
            const <int>[14, 15, 16, 17, 18, 7, 8, 9, 10, 11, 12],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix0.FormDeclaration() : null},
            0,
            0,
            const <int>[],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'DynamicFieldAttribute',
            r'.DynamicFieldAttribute',
            134217735,
            1,
            const prefix0.Reflector(),
            const <int>[3, 4, 21],
            const <int>[14, 15, 16, 17, 18, 19, 20],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({order, label}) => b
                  ? prefix0.DynamicFieldAttribute(label: label, order: order)
                  : null
            },
            0,
            1,
            const <int>[],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'MyModel',
            r'.MyModel',
            134217735,
            2,
            const prefix0.Reflector(),
            const <int>[5, 6, 24],
            const <int>[14, 15, 16, 17, 18, 22, 23],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({name, age}) =>
                  b ? prefix0.MyModel(age: age, name: name) : null
            },
            0,
            2,
            const <int>[],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'name', 67239941, 0, const prefix0.Reflector(),
            -1, 3, 3, const <int>[], const <Object>[
          const prefix0.DynamicFieldAttribute(
              label: 'Name and Surname', order: 1)
        ]),
        r.VariableMirrorImpl(r'age', 67239941, 0, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const <Object>[
          const prefix0.DynamicFieldAttribute(label: 'Age', order: 2)
        ]),
        r.VariableMirrorImpl(r'isMarried', 67239941, 0,
            const prefix0.Reflector(), -1, 5, 5, const <int>[], const <Object>[
          const prefix0.DynamicFieldAttribute(
              label: 'Are you married?', order: 3)
        ]),
        r.VariableMirrorImpl(r'label', 134349829, 1, const prefix0.Reflector(),
            -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(r'order', 134349829, 1, const prefix0.Reflector(),
            -1, 7, 7, const <int>[], const []),
        r.VariableMirrorImpl(r'name', 134349829, 2, const prefix0.Reflector(),
            -1, 6, 6, const <int>[], const []),
        r.VariableMirrorImpl(r'age', 134349829, 2, const prefix0.Reflector(),
            -1, 6, 6, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 7),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 8),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 9),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 10),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 11),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 2, 12),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 8, 8, const <int>[],
            const <int>[3], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 6, 6, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1,
            const <int>[], const <int>[4], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 9, 9, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 3, 19),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 4, 20),
        r.MethodMirrorImpl(r'', 128, 1, -1, 1, 1, const <int>[],
            const <int>[5, 6], const prefix0.Reflector(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 5, 22),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 6, 23),
        r.MethodMirrorImpl(r'', 0, 2, -1, 2, 2, const <int>[],
            const <int>[7, 8], const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'_name', 67240038, 8, const prefix0.Reflector(),
            -1, 3, 3, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'_age', 67240038, 10, const prefix0.Reflector(),
            -1, 4, 4, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_isMarried',
            67240038,
            12,
            const prefix0.Reflector(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            14,
            const prefix0.Reflector(),
            -1,
            10,
            10,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            16,
            const prefix0.Reflector(),
            -1,
            11,
            11,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'order',
            134358022,
            21,
            const prefix0.Reflector(),
            -1,
            7,
            7,
            const <int>[],
            const [],
            null,
            #order),
        r.ParameterMirrorImpl(
            r'label',
            134358022,
            21,
            const prefix0.Reflector(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            #label),
        r.ParameterMirrorImpl(r'name', 134358022, 24, const prefix0.Reflector(),
            -1, 6, 6, const <int>[], const [], null, #name),
        r.ParameterMirrorImpl(r'age', 134358022, 24, const prefix0.Reflector(),
            -1, 6, 6, const <int>[], const [], null, #age)
      ],
      <Type>[
        prefix0.FormDeclaration,
        prefix0.DynamicFieldAttribute,
        prefix0.MyModel,
        String,
        int,
        bool,
        String,
        int,
        bool,
        Type,
        Object,
        Invocation
      ],
      3,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'name': (dynamic instance) => instance.name,
        r'age': (dynamic instance) => instance.age,
        r'isMarried': (dynamic instance) => instance.isMarried,
        r'label': (dynamic instance) => instance.label,
        r'order': (dynamic instance) => instance.order
      },
      {
        r'name=': (dynamic instance, value) => instance.name = value,
        r'age=': (dynamic instance, value) => instance.age = value,
        r'isMarried=': (dynamic instance, value) => instance.isMarried = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(
                'package:extension_methods_test/mixin/json_extension.dart'),
            const prefix0.Reflector(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
