// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj14EOCcOTUphRXA-MPs_1pENEmhnMNC4',
    appId: '1:1022816616395:android:4787e3acd573c162b9c04e',
    messagingSenderId: '1022816616395',
    projectId: 'sharing-memo',
    storageBucket: 'sharing-memo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe6A7nbsQ1PNu9GdEO4b2VB-BbJALsNBM',
    appId: '1:1022816616395:ios:f2ca135de1ae161fb9c04e',
    messagingSenderId: '1022816616395',
    projectId: 'sharing-memo',
    storageBucket: 'sharing-memo.firebasestorage.app',
    androidClientId:
        '1022816616395-0ru6ukijjo0oa6kj4ud02d6gvv4u8pj1.apps.googleusercontent.com',
    iosClientId:
        '1022816616395-i1sm36bhje7hpuaq8e6smo0gbo4t9fdt.apps.googleusercontent.com',
    iosBundleId: 'dev.ej.sharingMemo',
  );
}
